Repository mapfish/mapfish-print, pull requests merged in 2022-11, with the labels that each got.

#2668 Fix repository in workflow used to delete old workflow runs
  .github/workflows/delete-old-workflows-run.yaml
Labels: chore

#2671 Fix handling of tables with mixed numeric columns
  core/src/main/java/org/mapfish/print/processor/jasper/TableProcessor.java
  core/src/test/resources/org/mapfish/print/processor/jasper/table-dynamic/config.yaml
  core/src/test/resources/org/mapfish/print/processor/jasper/table-dynamic/expectedImage.png
  core/src/test/resources/org/mapfish/print/processor/jasper/table-dynamic/requestData.json
Labels: bug

#2688 Add or update pull request check on stabilization branch
  .github/workflows/pr-checks.yaml
Labels: chore

#2690 Add or update pull request check on stabilization branch
  .github/workflows/pr-checks.yaml
Labels: chore

#2689 Add or update pull request check on stabilization branch
  .github/workflows/pr-checks.yaml
Labels: chore

#2691 Fix auto-review on stabilization of the branch for Renovate pull requests
  .github/workflows/auto-review.yaml
  .github/workflows/dependabot-auto-merge.yaml
Labels: chore

#2683 Fix CVE
  core/build.gradle
Labels: backport 3.29

#2692 Fix auto-review on stabilization of the branch for Renovate pull requests
  .github/workflows/auto-review.yaml
  .github/workflows/dependabot-auto-merge.yaml
  ci/config.yaml
Labels: chore

#2711 Fix vulnerabilities in indirect dependency
  core/build.gradle
Labels: backport 3.27, backport 3.28
